Added header headline
Berkay-akbas/Portfolio-Page pull request #1
Opened 2022-05-25 20:33 UTC by Berkay-akbas

2022-05-25 21:07 UTC, ShahierNashaat requested changes
Hi @Berkay-akbas , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 21:07 UTC, ShahierNashaat commented on index.html
> +      <h1>Berkay Akbas</h1>
- [ ] Kindly be noticed that the logo should be in an `a` tag.

2022-05-25 21:07 UTC, ShahierNashaat commented on index.html
> +      <a href="#">
- [ ] Kindly be noticed that the hamburger button should be inside a `nav` tag.

2022-05-25 21:07 UTC, ShahierNashaat commented on index.html
> +    <h3>I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded,
- [ ] It is better to replace the `h3` tag with the `p` tag as it is better for SEO.

2022-05-25 21:07 UTC, ShahierNashaat commented on index.html
> +    </footer>
- [ ] Kindly be noticed that the list of icons should use a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag).

2022-05-26 07:08 UTC, topeogunleye approved these changes
### Hi @Berkay-akbas, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * [ ]  Because the previous reviewer did not mention this, I also kindly suggest that you add a descriptive title and description to your PR. Here's a video on how to do so below:

https://user-images.githubusercontent.com/52934128/170152675-114d583f-dc6a-46ce-964a-c2d6cbb30ecf.mp4
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 07:08 UTC, topeogunleye commented on index.html
> +        <h1>Berkay Akbas</h1>
- [ ] [OPTIONAL] There should be only one `h1` in an HTML file because of semantics. I kindly suggest that you make only your main title of "Hey There. I'm Berkay" an `h1`.

2022-05-26 07:39 UTC, merged