Add about and works
Berkay-akbas/Portfolio-Page pull request #3
Opened 2022-05-26 20:15 UTC by Berkay-akbas

Sections Works and About me added.

2022-05-26 20:51 UTC, ShahierNashaat requested changes
Hi @Berkay-akbas , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 20:51 UTC, ShahierNashaat commented on index.html
> +      <p>My Recent Works</p>
- [ ] Kindly be noticed that the title `My Recent Works` should be inside an `hx` tag.

2022-05-26 20:51 UTC, ShahierNashaat commented on index.html
> +  </section>
- [ ] Kindly be noticed that you should put all of the about content in one `section` tag.
- [ ] Kindly be noticed that the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`.

2022-05-26 20:51 UTC, ShahierNashaat commented on styles.css
> +}
- [ ] It is better to add for this `ul` padding: 0 so when it shows in the center of the page.

2022-05-26 21:29 UTC, Berkay-akbas commented on index.html
> +  </section>
Hello, thank you for your feedback and I'm sorry I don't understand what you mean by the second line.  Could you elaborate, please?

2022-05-26 22:06 UTC, ShahierNashaat commented on index.html
> +  </section>
The "Languages", "Frameworks" and "Skills" all have to be inside of a one `ul` tag and each one of them should be inside a `li` tag and inside that `li` tag create a `ul` tag like you have created and add inside it the `li` tags like this.

```
<ul>
<li>
<p><img class="about_icon1" src="images/Rectangle55.png" alt="icon">Language</p>
    <ul class="language">
      <li>Javascipt</li>
      <li>Ruby</li>
      <li>Html</li>
      <li>Css</li>
    </ul>
</li>
<li>
    <p><img class="about_icon2" src="images/Rectangle56.png" alt="icon">Frameworks</p>
    <ul class="Frameworks">
      <li>Bootstrap</li>
      <li>Ruby on Rails</li>
      <li>RSPec</li>
      <li>CapyBara</li>
      <li>Selenium</li>
    </ul>
</li>
<li>
    <p><img class="about_icon3" src="images/Rectangle57.png" alt="icon">Skills</p>
    <ul class="Skills">
      <li>Codekit</li>
      <li>Github</li>
      <li>Codepen</li>
      <li>Gitlab</li>
      <li>Terminal</li>
    </ul>
</li>
</ul>
```

2022-05-26 22:20 UTC, Berkay-akbas commented on index.html
> +  </section>
Much appreciated!

2022-05-26 23:49 UTC, mukhammadrizooff requested changes
Hi @Berkay-akbas , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
- All linters passed 💯 
- Correct use of Gitflow 💯 
- Descriptive messages 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 23:49 UTC, mukhammadrizooff commented on styles.css
> +
- [ ] [RQUIRED] Please make changes! The technology categories ("Languages", "Frameworks" and "Skills") should true use the margins (top, bottom, left, right) defined in the design. 

![image](https://user-images.githubusercontent.com/63915024/170601690-1e9a5813-4a3c-46e2-acb4-94d3543a6528.png)

2022-05-26 23:49 UTC, mukhammadrizooff commented on styles.css
> +}
- [ ] [OPTIONAL] Good job! Please use colors in [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1).

![image](https://user-images.githubusercontent.com/63915024/170596693-26119794-fe54-441c-bef0-eceede231bae.png)

2022-05-27 10:46 UTC, vic778 approved these changes
## Hi @Berkay-akbas  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-05-27 10:48 UTC, merged