Style for desktop version
Berkay-akbas/Portfolio-Page pull request #6
Opened 2022-06-01 21:18 UTC by Berkay-akbas

Desktop version for the main section added.

2022-06-01 22:26 UTC, omarsalem7 requested changes
Hi @Berkay-akbas, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 22:26 UTC, omarsalem7 commented on styles.css
> +  }
- [ ] Consider adding `display: none;` for the See Project button In the desktop version to match the Figma template.

- Figma template
![image](https://user-images.githubusercontent.com/53402600/171511219-515d457d-8377-4823-aba7-c041745d1bbc.png)
- [ ] Consider also using the correct font color for languages in the card
- Figme template
![image](https://user-images.githubusercontent.com/53402600/171511575-48c85ecf-f586-4985-9e74-eae67130319a.png)

2022-06-01 22:26 UTC, omarsalem7 commented on styles.css
> +    grid-template-columns: repeat(3, minmax(300px, 1fr));
- [ ] You make a great work to make your portfolio responsive but it will be better if use `grid-template-columns: repeat(3, minmax(30%, 1fr));` instead of `grid-template-columns: repeat(3, minmax(300px, 1fr));` to make your website more responsive.

2022-06-02 07:00 UTC, OmarRamoun approved these changes
# 🟢 Project Approved! 🏆

## Hi @Berkay-akbas 👋

Your project is complete! ✔️ 🏁

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️
- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 07:41 UTC, merged